# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('serie', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=32)),
                ('modelo', models.CharField(max_length=1)),
            ],
        ),
    ]
