# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='modelo',
            field=models.CharField(choices=[('1', 'Small'), ('4', 'Medium')], max_length=1),
        ),
    ]
