# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_auto_20170506_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='modelo',
            field=models.CharField(choices=[('1', 'XO-1'), ('2', 'XO-1.5'), ('3', 'XO-1.75'), ('4', 'XO-4')], max_length=1),
        ),
    ]
